version: '3.1'

services:
  db:
    image: postgres
    restart: always
    # image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      # MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
      # MYSQL_DATABASE: ${TYPEORM_DATABASE}
      # MYSQL_USER: ${TYPEORM_USERNAME}
      # MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
      # POSTGRES_ROOT_PASSWORD: ${TYPEORM_PASSWORD}

      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
  
    ports:
      - ${TYPEORM_PORT}:5432